Revert "sctp: Do not wake readers in __sctp_write_space()"
Not applicable.

../net/sctp/socket.c:7780:43: error: use of undeclared identifier 'EPOLLOUT'
 7780 |                                 wake_up_interruptible_poll(&wq->wait, EPOLLOUT |
      |                                                                       ^
../net/sctp/socket.c:7781:7: error: use of undeclared identifier 'EPOLLWRNORM'
 7781 |                                                 EPOLLWRNORM | EPOLLWRBAND);
      |                                                 ^
../net/sctp/socket.c:7781:21: error: use of undeclared identifier 'EPOLLWRBAND'
 7781 |                                                 EPOLLWRNORM | EPOLLWRBAND);
      |                                                               ^
3 errors generated.

This reverts commit 7e82d15a6c9f39bedf167ed86fd4bc6049907c22.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>